[package]
name = "rust_sim"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulinalg = "0.4.2"
rand = "0.8.4"
rust_decimal = "1.17.0"
statrs = "0.15.0"
rayon = "1.5.1"
